import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getAuthSession } from "@/lib/nextauth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quiz-master",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch session server-side
  const session = await getAuthSession();
  console.log("Fetched session:", session); // Log the session

  return (
    <html lang="en">
      <body className={`antialiased min-h-screen pt-16 ${inter.className}`}>
        <Navbar session={session} />
        {children}
      </body>
    </html>
  );
}
